networks:
  go-server:
    driver: bridge

services:
  
  # db:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: indiamart
  #     MONGO_INITDB_ROOT_PASSWORD: indiamart@123
  #   expose:
  #     - 27017:27017
  #   ports:
  #     - "27017:27017" 
  #   volumes:
  #     - mongo-db:/data/db
  #   networks:
  #     - go-server

  backend:
    build: .
    networks:
      - go-server
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      DB_URL: "mongodb+srv://indiamart:indiamart%40123@cluster0.kr7rngt.mongodb.net/"
      GIN_MODE: "release"
      DBNAME: "postmanData"
      REQDATA: "reqData"
      REQINFO: "reqInfo"
      DOCKER: "yes"
      TESTDATA: "testData"
    extra_hosts:
      - "host.docker.internal:host-gateway"

# volumes:
#   mongo-db: 